language: c
compiler:
- gcc
os:
- linux
sudo: false
addons:
  apt:
    sources:
        - deadsnakes
    packages:
        - python3.4
before install:
- alias python3=python3.4
- which python3
script:
- make hardDisk
